<!-- Datei zur Anzeige des Chapterlinks und der Chapterlänge in einer Tabelle -->
<div class="box">
    <h2>
    </h2>

    <div class="block">
        <?php
        if ($this->block == 'video') {
            echo "<tr>";
            echo "<td align=\"left\">";
            echo "<a target=_blank href=$this->urlclips>$this->headlineclips</a>";
            echo "</td>";

            echo "<td align=\"right\">";
            $duration = new DateInterval($this->durationclips); #Parsen des Queries videoLectureClips (in videoLecture.phtml) in $duration
            echo $duration->format('%i:%S');
            echo "</td>";
            echo "</tr>";
        } else if ($this->block == 'time') {
            echo "|";
            echo $this->dateClips;
        }

        ?>

    </div>
</div>