<!-- Datei zur Darstellung einer ul der beinhaltenden Module einer Videovorlesung. Aufruf in aboutQuery.phtml -->
<div class="box">
    <h2>
    </h2>
        <div class="block">
            <ul>
                <li>
                    <?php
                    echo "<a target=_blank href=$this->url>$this->label</a>"
                    ?>
                </li>
            </ul>
        </div>
</div>