<!-- Darstellung Name, Logo, Beschreibung, Link einer Videovorlesung. Aufruf in videoLecture.phtml -->
<div class="box">
    <div class="block">
        <table class="table-responsive">
            <tr>
                <td>
                    <?php
                    echo "<h4>" . $this->headline . "<span style='font-size: 70%;'>".str_repeat('&nbsp;', 10)."erstellt im ".$this->time."</span></h4>";
                    ?>
                </td>
                <td width="16%" align="center">
                    <?php
                    echo "<a target=_blank ><img src='http://fbwbmakewiki2.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/$this->thumbnail' class='img-responsive' alt='Logo' width='304' height='236'></a>"
                    ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?php
                    echo $this->description;
                    ?>
                </td>
            </tr>

            <tr align="center">
                <td align="center" colspan="2">
                    <?php
                    echo "<a target=_blank href=$this->url width='30' height='30'><img src='http://fbwbmakewiki2.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/play_button.png' alt='Cinque Terre' width='32' height='32'></a>";
                    echo "<br> Zur Videovorlesung";
                    ?>
                </td>
            </tr>
        </table>
    </div>
</div>