<!-- Darstellung Name, Logo, Beschreibung, Link einer Videovorlesung. Aufruf in videoLecture.phtml -->
<div class="box">
    <div class="block">
        <table class="table-responsive">
            <tr>
                <td>
                    <?php
                    $months = array("01"=>"Jan. ", "02"=>"Feb. ", "03"=>"M&auml;rz ", "04"=>"Apr. ", "05"=>"Mai ", "06"=>"Jun. ", "07"=>"Jul. ", "08"=>"Aug. ", "09"=>"Sep. ", "10"=>"Okt. ", "11"=>"Nov. ", "12"=>"Dez. ");
                    $month = date_format($this->time, "m");
                    $month = $months[$month];
                    $year = date_format($this->time, "Y");
                    echo "<h4>" . $this->headline . "<span style='font-size: 70%;'>".str_repeat('&nbsp;', 10)."erstellt im ".$month.$year."</span></h4>";
                    ?>
                </td>
                <td width="16%" align="center">
                    <?php
                    echo "<a target=_blank ><img src='https://fbwtube.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/$this->thumbnail' class='img-responsive' alt='Logo' width='304' height='236'></a>"
                    ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?php
                    echo $this->description;
                    ?>
                </td>
            </tr>

            <tr align="center">
                <td align="center" colspan="2">
                    <?php
                    echo "<a target=_blank href=$this->url width='30' height='30'><img src='https://fbwtube.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/play_button.png' alt='Cinque Terre' width='32' height='32'></a>";
                    echo "<br> Zur Videovorlesung";
                    ?>
                </td>
            </tr>
        </table>
    </div>
</div>