<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
/**
 * example site extension layout template
 */

// this is the standard template data
$templateData = $this->templateData;

$logo_link = "https://drive.google.com/uc?export=view&id=17E26Sc9nfJth8aqTtZ5RktrrysFMjE1h";
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/"
      xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title>
        <?= $templateData['title'] ?> &mdash; <?= $this->siteConfig['name'] ?>
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="generator" content="<?= $this->generator ?>"/>

    <link rel="alternate" type="application/rdf+xml" href="<?= $this->resourceUri ?>.rdf"/>
    <link rel="pingback" href="<?= $this->pingbackUrl ?>"/>

    <link rel="shortcut icon" type="image/x-icon" href=<?= $logo_link ?>/>

    <link rel="<?= $this->curie("http://xmlns.com/foaf/0.1/primaryTopic") ?>" href="<?= $this->resourceUri ?>"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap.css" rel="stylesheet"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/layout.css" rel="stylesheet"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/sticky-footer-navbar.css" rel="stylesheet"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap.css.map"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap-theme.css.map"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap-glyphicons.css"/>
    <link type="text/css" href="<?= $this->baseUri ?>/css/modifications.css" rel="stylesheet"/>
    <link type="text/css" rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


    <!-- jQuery -->
    <script type="text/javascript" src="<?= $this->baseUri ?>/js/jquery.js"></script>

    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php
    // includes the GA header script
    // includes the exhibit header links
    // other head scripts
    $this->headScript();
    ?>
</head>

<body
    <?php foreach ($this->namespaces as $prefix => $ns): ?>
        <?= ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>
<div id="wrap">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"
                   href="https://fbwtube.th-brandenburg.de/OntoWiki/fbwTube/Home"><img
                            style="max-width:36px; margin-top: -10px;"
                            src=<?= $logo_link ?>>
                    fbwTube</a>
            </div>
            <?php
            $search = '
                      <div style="margin-bottom: 04px; margin-top: 08px;">
                          <form method="GET" id="filter_form" action="https://fbwtube.th-brandenburg.de/OntoWiki/fbwTube/VideoVorlesungen.html">
                              <div class="input-group">
                                  <input class="form-control" type="text" placeholder="Suchen..." name="search" value=' . htmlspecialchars($_GET['search']) . '>
                                  <span class="input-group-btn" style="width: auto">
                                  <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                  </span>
                              </div>
                          </form>
                      </div>
                        ';
            $navResource = $this->templateOptions()->getValue('http://rdfs.org/ns/void#rootResource');
            $navOptions = array(
                'navResource' => $navResource,
                'navId' => 'navbar-main',
                'suffix' => $search,
                'activeUrl' => $this->resourceUri,
                'listClass' => 'nav navbar-nav',
                'navClass' => 'navbar-collapse collapse'
            );
            ?>


            <?= $this->navigationList($navOptions) ?>


            <?php
            #echo $this->navigationList($navOptions);
            ?>

        </div>

    </div>

    <div class="container">
        <?= $this->renderx(); ?>
        <!-- Example row of columns for a Feed -->
        <div class="row">
            <?= $this->partial('example/types/feed.phtml', $this->templateData) ?>
        </div>
    </div> <!-- /container -->
    <div class="pull-right">
        <button class="btn btn-default toTop"><span class="glyphicon glyphicon-chevron-up"></span></button>
    </div>
</div>
<div id="footer">
    <div class="container">
        <p class="text-muted">&copy; Technische Hochschule Brandenburg - Fachbereich Wirtschaft 2018 &bull; <a
                    href="https://fbwtube.th-brandenburg.de/OntoWiki/fbwTube/Impressum">Impressum</a></p>
    </div>
</div>

<script type="text/javascript" src="<?= $this->baseUri ?>/js/jquery.js"></script>
<script type="text/javascript" src="<?= $this->baseUri ?>/js/bootstrap.js"></script>
<script type="text/javascript" src="<?= $this->baseUri ?>/js/custom.js"></script>

</body>
</html>
