<div class="page-header">
    <h2><?php echo $this->title ?></h2>
</div>
<div class="jumbotron">
    <h2>

    </h2>

    <?php
    $id = $_GET['id'];
    ?>

    <?php
    $videoLectureQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
    $videoLectureQuery .= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
    $videoLectureQuery .= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
    $videoLectureQuery .= 'SELECT ?description ?url ?headline ?about ?thumbnail' . PHP_EOL;
    $videoLectureQuery .= 'WHERE {<';
    $videoLectureQuery .= $id;
    $videoLectureQuery .= '> schema:description ?description ;' . PHP_EOL;
    $videoLectureQuery .= 'schema:headline ?headline ;' . PHP_EOL;
	$videoLectureQuery .= 'schema:url ?url ;' . PHP_EOL;
    $videoLectureQuery .= 'schema:thumbnail ?logo .' . PHP_EOL;
	$videoLectureQuery .= '?logo schema:name ?thumbnail .' . PHP_EOL;
#    $videoLectureQuery .= 'schema:about ?about .' . PHP_EOL;
    $videoLectureQuery .= 'FILTER( lang(?headline) = "de")' . PHP_EOL;
    $videoLectureQuery .= '}' . PHP_EOL;
    ?>

    <?php
    $videoLectureAboutQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
    $videoLectureAboutQuery .= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
    $videoLectureAboutQuery .= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
    $videoLectureAboutQuery .= 'SELECT ?about' . PHP_EOL;
    $videoLectureAboutQuery .= 'WHERE {<';
    $videoLectureAboutQuery .= $id;
    $videoLectureAboutQuery .= '> schema:about ?about .' . PHP_EOL;
    $videoLectureAboutQuery .= '}' . PHP_EOL;
    ?>
    <?= $this->querylist($videoLectureQuery, 'vidp/types/videoInfo.phtml', array()) ?>
    <h5>
        Diese Videovorlesung ist Bestandteil folgender Module:
    </h5>
    <?= $this->querylist($videoLectureAboutQuery, 'vidp/types/videoInfo.phtml', array()) ?>


</div>