<div class="box">
    <h2>
    </h2>
    <?php if ($this->about) : ?>
    <?php    
        $moduleQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
        $moduleQuery .= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
        $moduleQuery .= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
        $moduleQuery .= 'SELECT ?label ?url' . PHP_EOL;
        $moduleQuery .= 'WHERE {<';
        $moduleQuery .= $this->about;
        $moduleQuery .= '> schema:url ?url ;' . PHP_EOL;
        $moduleQuery .= 'rdfs:label ?label .' . PHP_EOL;
        $moduleQuery .= '}' . PHP_EOL;

        echo $this->querylist($moduleQuery, 'vidp/types/moduleInfo.phtml', array());
    ?>
    <?php else: ?>
        <div class="block">
            <table class="table-responsive">
                <tr>
                    <td>
                        <?php
                        echo "<h4>" . $this->headline . "</h4>"
                        ?>
                    </td>
                    <td width="16%" align="center">
                        <?php
                        echo "<a target=_blank ><img src='http://fbwbmakewiki2.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/$this->thumbnail' class='img-responsive' alt='Logo' width='304' height='236'></a>"
                        ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?php
                        echo $this->description;
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php
                        echo $this->about;
                        ?>
                    </td>
                </tr>
                <tr align="center">
                    <td align="center" colspan="2">
                        <?php
                        echo "<a target=_blank href=$this->url width='30' height='30'><img src='http://fbwbmakewiki2.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/play_button.png' alt='Cinque Terre' width='32' height='32'></a>";
                        echo "<br> Zur Videovorlesung";
                        ?>
                    </td>
                </tr>
            </table>
        </div>
    <?php endif; ?>
</div>