<div class="page-header">
    <h1><?php echo $this->title ?>
        <small>fuer FBW-Tube</small>
    </h1>
</div>
<div class="jumbotron">
    <?php
    $videoLectureElementQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
    $videoLectureElementQuery .= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
    $videoLectureElementQuery .= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
    $videoLectureElementQuery .= 'SELECT ?videoLecture ?headline' . PHP_EOL;
    $videoLectureElementQuery .= 'WHERE {?videoLecture rdf:type vidp:VideoLecture;' . PHP_EOL;
    $videoLectureElementQuery .= 'schema:headline ?headline.' . PHP_EOL;
    $videoLectureElementQuery .= 'FILTER( lang(?headline) = "de")' . PHP_EOL;
    $videoLectureElementQuery .= '}' . PHP_EOL;
    ?>

    <h4><?= $this->_('Video Lectures') ?></h4>
    <ul>
        <?= $this->querylist($videoLectureElementQuery, 'vidp/types/videoLectureElement.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>')) ?>
    </ul>
</div>

