<div class="page-header">
  <h1><?php echo $this->title ?> <small>fuer FBW-Tube</small></h1>
</div>
<div class="jumbotron">
<?php
    // uses default content properties
    echo $this->literal(array('tag' => 'div', 'class' => 'content'));
?>
</div>
<div class="jumbotron">
<?php
    $headlineQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
    $headlineQuery.= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
    $headlineQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
    $headlineQuery.= 'SELECT ?videoLecture' . PHP_EOL;
    $headlineQuery.= 'WHERE {?videoLecture rdf:type vidp:VideoLecture.' . PHP_EOL;
    $headlineQuery.= '}' . PHP_EOL;
?>

<h4><?= $this->_('Video Lectures') ?></h4>
<ul>
   <?= $this->querylist($headlineQuery, 'local/types/person.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>')) ?>

</ul>
<!--    <?php
	echo $headlineQuery->literal(array('property' => 'schema:headline'));
    ?>
-->
</div>

