<!-- Datei zur Darstellung aller Videovorlesungen als Liste -->

<head>
    <!-- Laden des Scripts zum Aktivieren des Zustandes "Indeterminate" für Checkboxes -->
    <script type="text/javascript" src="<?= $this->baseUri ?>/js/indeterminate.js"></script>
</head>
<body OnLoad="document..focus();">
<?php
session_start();
?>
<div class="page-header">
    <h2><?php echo $this->title ?></h2>
</div>


<!-- Erzeugen des Buttons zum Ein- und Ausblenden des Filterareas -->
<button type="button" id="filterButton" class="btn btn-success btn-lg btn-block" aria-pressed="true"
        data-toggle="collapse"
        data-target="#filter" style="margin-bottom: 30px"><i class="fas fa-filter"></i> &nbsp;
    Filtern
</button>

<!-- Script zum visuellen Aktivieren und Deaktivieren beim Klicken des Buttons "Filtern" -->
<script language="JavaScript" type="text/javascript">
    $('#filterButton').on('click', function (e) {
        $('#filterButton').each(function () {
            if ($(this).hasClass('active')) {
                $(this).removeClass('active');
            } else {
                $(this).addClass('active');
            }
        })
    });
</script>

<?php
#Diese Query ist nur für Auflisten der Lehrenden als checkboxes.
$lecturerQuery = "PREFIX ns2: <https://bmake.th-brandenburg.de/vidp#>
                  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                  SELECT DISTINCT ?lecturer
                  WHERE {
                  ?lecturerURI a ns2:Lecturer;
                  rdfs:label ?lecturer.
                  }";

?>

<?php
#Hier werden die einzelnen Lehrenden in ein Array geschrieben, um später einfacher aufgelistet werden zu können.
$_SESSION['lecturers'] = array();
$this->querylist($lecturerQuery, 'vidp/types/videoLectureList/filterNames.phtml');

?>

<?php
#Diese Query ist nur für Auflisten der Module als Dropdown-Menü.
$moduleQuery = "PREFIX ns2: <https://bmake.th-brandenburg.de/vidp#>
                PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                SELECT DISTINCT ?module
                WHERE {
                ?moduleUri a ns2:Module;
                rdfs:label ?module.
                }";
?>

<?php
#Hier werden die einzelnen Module in ein Array geschrieben, um später einfacher aufgelistet werden zu können.
$_SESSION['modules'] = array();
$this->querylist($moduleQuery, 'vidp/types/videoLectureList/filterNames.phtml');

?>


<?php
#Diese Query ist nur für Auflisten der Studiengänge als Dropdown-Menü.
$studyProgramQuery = "PREFIX ns2: <https://bmake.th-brandenburg.de/vidp#>
                      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                      SELECT DISTINCT ?studyProgram
                      WHERE {
                      ?studyProgramUri a ns2:StudyProgram;
                      rdfs:label ?studyProgram.
                      }";
?>

<?php
#Hier werden die einzelnen Studiengänge in ein Array geschrieben, um später einfacher aufgelistet werden zu können.
$_SESSION['studyPrograms'] = array();
$this->querylist($studyProgramQuery, 'vidp/types/videoLectureList/filterNames.phtml');

?>

<!-- Erzeugung des Formulars für die Filter -->
<div id="filter" class="collapse jumbotron container-fluid">
    <form method="GET" id="search_form" name="search_form">
        <input type="hidden" id="pageID" name="pageID" form="search_form" value="1">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <table class="table responsive">
                    <thead>
                    <tr>
                        <th class="text-left"><i class="fas fa-globe-americas"></i> &nbsp; Sprache</th>
                    </tr>
                    </thead>
                    <tr>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="en" form="search_form" onclick="toggle(this)"
                                       id="lang1" name="lang1" <?php echo($_GET["lang1"] == "en" ? "checked" : "") ?>>
                                <!-- Kontrollieren, ob Checbox gesetzt wurde -->
                                <label class="form-check-label" for="lang1">
                                    Englisch
                                </label>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="de" form="search_form" onclick="toggle(this)"
                                       id="lang2" name="lang2" <?php echo($_GET["lang2"] == "de" ? "checked" : "") ?>>
                                <!-- Kontrollieren, ob Checbox gesetzt wurde -->
                                <label class="form-check-label" for="lang2">
                                    Deutsch
                                </label>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4 col-sm-6">
                <table class="table responsive">
                    <thead>
                    <tr>
                        <th class="text-left"><i class="fas fa-user"></i> &nbsp; Dozent(in)</th>
                    </tr>
                    </thead>
                    <?php
                    #Generische Erzeugung der Checkbox-Liste für Lehrende
                    for ($i = 0; $i < count($_SESSION['lecturers']); $i++) {
                        $currentLecturer = $_SESSION['lecturers'][$i];
                        $currentCheckBoxName = "lecturer" . ($i + 1);
                        $currentCheckBox = '<tr>';
                        $currentCheckBox .= '<td>';
                        $currentCheckBox .= '<div class="form-check">';
                        $currentCheckBox .= '<input class="form-check-input" type="checkbox" value="' . $currentLecturer . '" form="search_form" onclick="toggle(this)" id="' . $currentCheckBoxName . '"';
                        $currentCheckBox .= 'name="' . $currentCheckBoxName . '"' . ($_GET[$currentCheckBoxName] == $currentLecturer ? "checked" : "") . '>';
                        $currentCheckBox .= '<label class="form-check-label" for=' . $currentCheckBoxName . '>';
                        $currentCheckBox .= '&nbsp;' . $currentLecturer;
                        $currentCheckBox .= '</label>';
                        $currentCheckBox .= '</div>';
                        $currentCheckBox .= '</td>';
                        $currentCheckBox .= '</tr>';
                        echo $currentCheckBox;
                    }
                    ?>

                </table>
            </div>

            <div class="col-md-4">
                <table class="table responsive">
                    <thead>
                    <tr>
                        <th class="text-left"><i class="fas fa-book"></i> &nbsp; Modul</th>
                    </tr>
                    </thead>
                    <tr>
                        <td>
                            <select class="form-control responsive" name="module" form="search_form">
                                <?php
                                echo "<option value=''>--Bitte wählen Sie ein Modul aus--</option>";
                                #Generische Erzeugung der Dropdown-Menü für Module
                                for ($i = 0; $i < count($_SESSION['modules']); $i++) {
                                    $currentModule = $_SESSION['modules'][$i];
                                    $currentOption = '<option value="' . $currentModule . '" ' . ($_GET['module'] == $currentModule ? "selected" : "") . '>' . $currentModule . '</option>';
                                    echo $currentOption;
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                </table>
                <table class="table responsive">
                    <thead>
                    <tr>
                        <th class="text-left"><i class="fas fa-graduation-cap"></i> &nbsp; Studiengang</th>
                    </tr>
                    </thead>
                    <tr>
                        <td>
                            <select class="form-control responsive" name="studyProgram" form="search_form">
                                <?php
                                echo "<option value=''>--Bitte wählen Sie einen Studiengang aus--</option>";
                                #Generische Erzeugung der Dropdown-Menü für Studiengänge
                                for ($i = 0; $i < count($_SESSION['studyPrograms']); $i++) {
                                    $currentStudyProgram = $_SESSION['studyPrograms'][$i];
                                    $currentOption = '<option value="' . $currentStudyProgram . '" ' . ($_GET['studyProgram'] == $currentStudyProgram ? "selected" : "") . '>' . $currentStudyProgram . '</option>';
                                    echo $currentOption;
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row" align="center">
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-success" form="search_form" id="submit_filter"><i class="fas fa-check"></i>&nbsp; Anwenden</button>
                <!-- Button wird deaktiviert, wenn nichts ausgewählt wurde, also wenn $_GET leer ist.  -->
                <button type="reset" class="btn btn-danger"
                        onclick="location.href='/OntoWiki/fbwTube/VideoVorlesungen.html'">
                    <i class="fas fa-undo"></i>&nbsp; Zurücksetzen
                </button>
            </div>
        </div>
    </form>
</div>
<!-- Bereich für "Suche nach:"  -->
<?php
if ($_GET['search'] != "") {
    echo '<div class="panel panel-default"> <div class="panel-body">Ihre Suche nach:';
    $searchString= $searchString . ($_GET['search']);
    echo '<b> ' . $searchString . '</b>';
    if ($_GET["lang1"] != "" || $_GET["lang2"] != "" || lecturerList(count($_SESSION['lecturers'])) != ""  || $_GET['studyProgram'] != "" || $_GET['module'] != "") {
        echo ' mit folgenden Kriterien: ';
        if ($_GET["lang1"] != "") $searchCriteria= "Englisch" . ", " ;
        if ($_GET["lang2"] != "") $searchCriteria=  $searchCriteria . "Deutsch" . ", " ;
        if ($_SESSION['lecturers'] != "") $searchCriteria=  $searchCriteria . lecturerList(count($_SESSION['lecturers']));
        if ($_GET['studyProgram'] != "") $searchCriteria= $searchCriteria . ($_GET['studyProgram']) . ", " ;
        if ($_GET['module'] != "") $searchCriteria= $searchCriteria . ($_GET['module']) . ", ";
        $searchCriteria = substr_replace($searchCriteria ,"",-2);
        echo '<b>' . $searchCriteria . '</b>';
    }
    echo '</div> </div>';
}
if ($_GET['search'] == "" && ($_GET["lang1"] != "" || $_GET["lang2"] != "" || lecturerList(count($_SESSION['lecturers'])) != ""  || $_GET['studyProgram'] != "" || $_GET['module'] != "")) {
    echo '<div class="panel panel-default"> <div class="panel-body">Ihre Suchkriterien: ';
        if ($_GET["lang1"] != "") $searchCriteria= "Englisch" . ", " ;
        if ($_GET["lang2"] != "") $searchCriteria=  $searchCriteria . "Deutsch" . ", " ;
        if ($_SESSION['lecturers'] != "") $searchCriteria=  $searchCriteria . lecturerList(count($_SESSION['lecturers']));
        if ($_GET['studyProgram'] != "") $searchCriteria= $searchCriteria . ($_GET['studyProgram']) . ", " ;
        if ($_GET['module'] != "") $searchCriteria= $searchCriteria . ($_GET['module']) . ", ";
        $searchCriteria = substr_replace($searchCriteria ,"",-2);
        echo '<b>' . $searchCriteria . '</b>';
        echo '</div> </div>';
    }
?>

<div class="jumbotron">
    <?php
    $videoLectureElementQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>
                                PREFIX schema: <https://schema.org/>
                                PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                                SELECT DISTINCT ?videoLecture ?headline ?thumbnail ?label ?description ?language
                                WHERE { ?videoLecture a vidp:VideoLecture ;
                                schema:description ?description ;
                                schema:thumbnail ?logo ;
                                schema:inLanguage ?language ;
                                rdfs:label ?label ;
                                schema:keywords ?keywords;
                                schema:headline ?headline .
                                ?logo schema:identifier ?thumbnail .
                                ?videoLecture a vidp:VideoLecture;
                                schema:about ?modul.
                                ?modul a vidp:Module;
                                rdfs:label ?modul_label .
                                ?modul schema:isPartOf ?studyProgram .
                                ?studyProgram rdfs:label ?labelStudyProgram .
                                FILTER ( lang(?headline) = "de" ) .
                                ?doubleClip schema:isPartOf ?videoLecture .';

    $lecturerChecked = false;
    $lecturerCount = count($_SESSION['lecturers']);
    #Diese for Schleife kontrolliert if eine der Checkboxes für die Filterfunktion "Lecturer" markiert wurde.
    for ($i = 0; $i < $lecturerCount; $i++) {
        if ($_GET["lecturer" . ($i + 1)] != "") {
            $lecturerChecked = true;
        }
    }
    #Dieser Block wird nur ausgeführt, falls eine der Checkboxes für die Filterfunktion "Lecturer" markiert ist.
    if ($lecturerChecked) {
        $videoLectureElementQuery .= '{
       	 ?doubleClip schema:creator ?creator.
         ?creator rdfs:label ?nameCreator.
         FILTER (';
        #Durch diese for Schleife sichergestellt, dass mehrere Dozenten ausgewählt werden können
        for ($i = 0; $i < $lecturerCount; $i++) {
            $videoLectureElementQuery .= 'CONTAINS( ?nameCreator, "' . $_GET["lecturer" . ($i + 1)] . '" )';
            if ($i < $lecturerCount - 1) {
                $videoLectureElementQuery .= ' || ';
            }
        }
        $videoLectureElementQuery .=
            ')}
       UNION { 
         ?doubleClip schema:contributor ?contributor. 
         ?contributor rdfs:label ?nameContributor. 
         FILTER (';
        #Durch diese for Schleife sichergestellt, dass mehrere Dozenten ausgewählt werden können
        for ($i = 0; $i < $lecturerCount; $i++) {
            $videoLectureElementQuery .= 'CONTAINS( ?nameContributor, "' . $_GET["lecturer" . ($i + 1)] . '" )';
            if ($i < $lecturerCount - 1) {
                $videoLectureElementQuery .= ' || ';
            }
        }
        $videoLectureElementQuery .=
            ')}' . PHP_EOL;
    }

    if ($_GET["lang1"] != "" || $_GET["lang2"] != "") {  //Query für Filterfunktion "Sprache"
        $videoLectureElementQuery .= 'FILTER ( (?language ="' . $_GET["lang1"] . '") 
            || (?language ="' . $_GET["lang2"] . '") ) .';
    }
    if ($_GET['module'] != "") {
        $videoLectureElementQuery .= 'FILTER (CONTAINS(?modul_label, "' . $_GET['module'] . '"))';
    }
    if ($_GET['studyProgram'] != "") {
        $videoLectureElementQuery .= 'FILTER (CONTAINS(?labelStudyProgram, "' . $_GET['studyProgram'] . '"))';
    }
    if ($_GET['search'] != "") {
        $searchWords = explode(' ', $_GET['search']);
        $videoLectureElementQuery .= 'FILTER (';
        foreach ($searchWords as $searchWord) {
            $videoLectureElementQuery .= ' REGEX(?keywords, "'. $searchWord .'", "i") || REGEX(?headline, "'. $searchWord .'", "i") || REGEX(?description, "'. $searchWord .'", "i") || ';
        }
        $videoLectureElementQuery = substr($videoLectureElementQuery, 0, -3) . " )";
        #$videoLectureElementQuery .= '} ORDER BY STRLEN(REPLACE(REPLACE(CONCAT(?headline, ?description,?keywords), "'. $searchWord .'", "#", "i"), "[^#]", ""))';
    }
    $videoLectureElementQuery .= '}';
    #Aufzählen der Elemente in $_GET um die Paginierung aktivieren oder deaktivieren
    $keyNum = 0;
    foreach ($_GET as $key => $value) {
        $keyNum++;
    }
    if ($keyNum == 0 || $keyNum == 1) {
        if (!isset($_GET["pageID"])) {
            $videoLectureElementQuery .= 'LIMIT 10';
        } else {
            $videoLectureElementQuery .=  'OFFSET ' . ($_GET["pageID"]-1) * 10;
            $videoLectureElementQuery .=  'LIMIT 10';
        }
    }
    $videoLectureElementQuery .= 'ORDER BY ?videoLecture';

    #}

    # Funktion für Lecturerlist für Suchkriterienliste
    function lecturerList($lecturerCount)
    {
        $lecturerList = null;
        for ($i = 0; $i < $lecturerCount; $i++) {
            if ($_GET["lecturer" . ($i + 1)] != "") {
                $lecturerList = $lecturerList . $_GET["lecturer" . ($i + 1)] . ", ";
            }
        }
        return $lecturerList;
    }
    ?>

    <?=
    # $this->querylist($videoLectureElementQuery, 'vidp/types/videoLectureElement.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>'))

    #Hier wird kontrolliert, ob die angewendte Query mindestens eine Vorlesung zurückgibt. Falls nicht, wird eine Nachricht angezeigt.
    $result = $this->querylist($videoLectureElementQuery, 'vidp/types/videoLectureList/videoLectureElement.phtml', array());
    if ($result == "") {
        echo "<h3>Die Suche lieferte keine Ergebnisse.</h3>";
    }
    ?>


    <script> toggleAllCheckboxesToIndeterminate(); </script>

    <?php #Diese Query ist zum Aufzählen der Videovorlesungen für die Paginierung.
          $videoLectureCountQuery =  'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>
                                      PREFIX schema: <https://schema.org/>
                                      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
                                      SELECT DISTINCT count(?videoLectures) AS ?VLC
                                      WHERE 
                                      {
                                        ?videoLectures a vidp:VideoLecture .
                                      }';
          $videoLectureCount = $this->querylist($videoLectureCountQuery, 'vidp/types/videoLectureList/videoLectureCount.phtml');
          $pageCount = $videoLectureCount / 10; #Paginierung durch jeweils 10 Videovorlesungen
          if ($videoLectureCount % 10 != 0) $pageCount++;
    ?>

</div>

<?php #Hier werden die Buttons für die Paginierung erzeugt.
    if ($keyNum == 0 || $keyNum == 1) {
    echo '<nav aria-label="Page navigation example" align="center">';
    echo '<ul class="pagination">';
            for ($i = 1; $i <= $pageCount; $i++){
                $active = ((!isset($_GET["pageID"]) && $i == 1) || isset($_GET["pageID"]) && $_GET["pageID"] == $i) ? 'active' : '';
                echo '<li class="page-item ' . $active . '"><a class="page-link" href="https://fbwtube.th-brandenburg.de/OntoWiki/fbwTube/VideoVorlesungen.html?pageID=' . $i . '" >' . $i . '</a></li>';
            }
    echo '</ul>';
    echo '</nav>';
}
?>