<!-- Datei zur Darstellung einzelner Videovorlesungen als Listenelement -->
<div class="box">
    <div class="block">
        <div class="block">
            <?php
            $base = "http://fbwbmakewiki2.th-brandenburg.de/OntoWiki/index.php/test/";
            $url = $base . "VideoVorlesung.html?id=" . urlencode($this->videoLecture);
            ?>

            <?php
            $videoLectureDurationQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
            $videoLectureDurationQuery .= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
            $videoLectureDurationQuery .= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
            $videoLectureDurationQuery .= 'SELECT ?durationclips' . PHP_EOL;
            $videoLectureDurationQuery .= 'WHERE { ?clips a vidp:DoubleClip;' . PHP_EOL;
            $videoLectureDurationQuery .= 'schema:isPartOf <';
            $videoLectureDurationQuery .= $this->videoLecture;
            $videoLectureDurationQuery .= '>; schema:duration	?durationclips. }' . PHP_EOL;
            ?>

            <?php
            $result = $this->querylist($videoLectureDurationQuery, 'vidp/types/videoLectureList/videoDuration.phtml', array(), array('prefix' => ' '));
            $result = trim($result);
            $result = array_map('intval', explode(' ', $result));

            $time = null;
            foreach ($result as $item) {
                $time = $time + $item;
            }
            ?>

            <table>
                <tr>
                    <td rowspan="2" width="20%" height="80">
                        <a href="<?= htmlentities($url) ?>"><?php echo "<img src='http://fbwbmakewiki2.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/$this->thumbnail' class='img-responsive' width='200' height='150'>" ?></a>
                    </td>
                    <td height="40" width="50%">
                        <font size="4">
                            <a href="<?= htmlentities($url) ?>"><b><?= $this->label ?></b></a>
                        </font>
                    </td>
                    <td align="right" width="20%">
                        <?php
                        echo sizeof($result);
                        echo " Teile | ";
                        echo "Gesamtdauer: ";
                        echo gmdate("H:i:s", $time);
                        ?>
                    </td>
                </tr>
                <tr>
                    <td valign="top" colspan="2">
                        <?=
                        strstr($this->description, ". ", true);
                        echo ". ";
                        ?>
                        <a href="<?= htmlentities($url) ?>">mehr</a>
                    </td>
                </tr>
            </table>
            <br>
        </div>
    </div>
</div>