<!-- Datei zur Darstellung einzelner Videovorlesungen als Listenelement -->
<div class="box">
    <div class="block">
        <?php
        $base = "https://fbwtube.th-brandenburg.de/OntoWiki/fbwTube/";
        $url = $base . "VideoVorlesung.html?id=" . urlencode($this->videoLecture);
        ?>

        <?php
        $videoLectureDurationQuery = 'PREFIX vidp: <https://bmake.th-brandenburg.de/vidp#>' . PHP_EOL;
        $videoLectureDurationQuery .= 'PREFIX schema: <https://schema.org/>' . PHP_EOL;
        $videoLectureDurationQuery .= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
        $videoLectureDurationQuery .= 'SELECT ?durationclips ?contributorname ?creatorname' . PHP_EOL;
        $videoLectureDurationQuery .= 'WHERE { ?clips a vidp:DoubleClip;' . PHP_EOL;
        $videoLectureDurationQuery .= 'schema:isPartOf <';
        $videoLectureDurationQuery .= $this->videoLecture;
        $videoLectureDurationQuery .= '>; schema:duration	?durationclips; 
                                           schema:creator ?creator. 
                                           ?creator rdfs:label ?creatorname.
                                           OPTIONAL { ?clips  schema:contributor  ?contributor.
                                           ?contributor rdfs:label ?contributorname.}}' . PHP_EOL;
        ?>

        <?php
        $result = $this->querylist($videoLectureDurationQuery, 'vidp/types/videoLectureList/videoDurationContributor.phtml', array('block' => 'duration'), array('prefix' => ' '));
        $result = trim($result);
        $result = array_map('intval', explode(' ', $result));

        $time = null;
        foreach ($result as $item) {
            $time = $time + $item;
        }

        $contributor = $this->querylist($videoLectureDurationQuery, 'vidp/types/videoLectureList/videoDurationContributor.phtml', array('block' => 'contributor'), array('prefix' => '|'));
        $contributor = explode('|', $contributor);
        unset($contributor[0]);
        $contributor = array_values(array_unique($contributor));

        $lecturer = "";
        foreach ($contributor as $item) {
            $lecturer = $lecturer . $item . "; ";
        }
        $lecturer = substr($lecturer, 0, strlen($lecturer) - 2);

        ?>

        <table class="table">
            <tr>
                <td rowspan="3" width="20%" height="80">
                    <a href="<?= htmlentities($url) ?>"><?php echo "<img src='https://drive.google.com/uc?export=view&id=$this->thumbnail' class='img-responsive' width='200' height='150'>" ?></a>
                    <!--https://fbwtube.th-brandenburg.de/OntoWiki/extensions/site/sites/vidp/img/-->
                </td>
                <td width="40%" height="40">
                    <font size="4">
                        <a href="<?= htmlentities($url) ?>"><b><?= $this->label ?></b></a>
                    </font>
                </td>
                <td align="right" width="30%">
                    <?php
                    echo "Sprache: " . $this->language . " | ";
                    echo sizeof($result);
                    if (sizeof($result) > 1) {
                        echo " Teile | ";
                    } else {
                        echo " Teil | ";
                    }
                    echo "Gesamtdauer: ";
                    echo gmdate("H:i:s", $time);
                    ?>
                </td>
            </tr>
            <tr>
                <td valign="top" colspan="2" width="70%">
                    <?=
                    strstr($this->description, ". ", true);
                    echo ". ";
                    ?>
                    <a href="<?= htmlentities($url) ?>">mehr</a>
                </td>
            </tr>
            <tr>
                <td valign="top" colspan="2" width="70%">
                    <i>
                        <?php echo $lecturer ?>
                    </i>
                </td>
            </tr>
        </table>
        <br>
    </div>
</div>